### ISSUE TITLE
Android built in backup: add for preference files

### ISSUE THREAD

**Issue by alceurneto** [ARNdroid/EasyTargetDietProject#179]

**Comment by ARNdroid** [comment]
Our NOT working tests on SII device.
After customizing values for shared preferences and running:
```$adb shell bmgr run```
Outputs in LogCat:
```02-21 06:36:00.120    2124-2135/? V/BackupManagerService? Scheduling immediate backup pass
02-21 06:36:00.125    2124-2166/? V/BackupManagerService? Running a backup pass
02-21 06:36:00.130    2124-2239/? V/BackupManagerService? clearing pending backups
02-21 06:36:00.140    2124-2239/? V/PerformBackupTask? Beginning backup of 3 targets
02-21 06:36:00.195    2124-2239/? V/BackupServiceBinder? doBackup() invoked
02-21 06:36:00.195    2124-2239/? D/PerformBackupTask? invokeAgentForBackup on @pm@
02-21 06:36:00.200    2124-2239/? I/PerformBackupTask? no backup data written; not calling transport
02-21 06:36:00.200    2124-2239/? D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.google.android.googlequicksearchbox}
02-21 06:36:00.535    2124-2239/? I/BackupManagerService? got agent android.app.IBackupAgent$Stub$Proxy@42ceb140
02-21 06:36:00.535    1580-1591/? V/BackupServiceBinder? doBackup() invoked
02-21 06:36:00.535    2124-2239/? D/PerformBackupTask? invokeAgentForBackup on com.google.android.googlequicksearchbox
02-21 06:36:00.540    1580-1591/? W/LauncherBackupHelper? Failed to get app state during backup/restore
    java.lang.Throwable
            at aai.ji(PG:1091)
            at aai.performBackup(PG:193)
            at android.app.backup.BackupHelperDispatcher.doOneBackup(BackupHelperDispatcher.java:95)
            at android.app.backup.BackupHelperDispatcher.performBackup(BackupHelperDispatcher.java:62)
            at android.app.backup.BackupAgentHelper.onBackup(BackupAgentHelper.java:66)
            at android.app.backup.BackupAgent$BackupServiceBinder.doBackup(BackupAgent.java:490)
            at android.app.IBackupAgent$Stub.onTransact(IBackupAgent.java:80)
            at android.os.Binder.execTransact(Binder.java:367)
            at dalvik.system.NativeStart.run(Native Method)
02-21 06:36:00.545    2124-2239/? D/BackupManagerService? Now staging backup of com.google.android.googlequicksearchbox
02-21 06:36:00.580    2124-2239/? I/PerformBackupTask? no backup data written; not calling transport
02-21 06:36:00.580    2124-2239/? D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=android}
02-21 06:36:00.595    2124-2166/? D/BackupManagerService? agentConnected pkg=android agent=android.app.backup.BackupAgent$BackupServiceBinder@428ae160
02-21 06:36:00.595    2124-2239/? I/BackupManagerService? got agent android.app.backup.BackupAgent$BackupServiceBinder@428ae160
02-21 06:36:00.595    2124-2239/? V/BackupServiceBinder? doBackup() invoked
02-21 06:36:00.595    2124-2239/? D/BackupHelperDispatcher? handling existing helper 'wallpaper' android.app.backup.WallpaperBackupHelper@4253af90
02-21 06:36:00.595    2124-2239/? D/PerformBackupTask? invokeAgentForBackup on android
02-21 06:36:01.090    2124-2239/? D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=br.com.arndroid.etdiet}
02-21 06:36:01.110    2124-2239/? I/BackupManagerService? got agent android.app.IBackupAgent$Stub$Proxy@425a9908
02-21 06:36:01.110    2124-2239/? D/PerformBackupTask? invokeAgentForBackup on br.com.arndroid.etdiet
02-21 06:36:01.115    1197-1217/? V/BackupServiceBinder? doBackup() invoked
02-21 06:36:01.115    1197-1217/? D/BackupHelperDispatcher? handling existing helper 'PREFERENCES_BACKUP' android.app.backup.SharedPreferencesBackupHelper@41e5e730
02-21 06:36:01.660    2124-2239/? I/PerformBackupTask? Backup pass finished.```

Running:
```$adb shell bmgr backup br.com.arndroid.etdiet```
Outputs in LogCat:
```02-21 06:47:13.110    2124-2239/? D/BackupManagerService? Now staging backup of br.com.arndroid.etdiet```

After an uninstall e re-install the shared preference is set to default values. :-(

**Comment by ARNdroid** [comment]
Our OK tests on emulator.

Enabling backup on emulator:
```$adb -s emulator-5554 shell bmgr enable true```
Outputs LogCat:
```02-21 09:49:33.127     880-1520/system_process I/BackupManagerService? Backup enabled => true```

Forcing a backup to run:
```$adb -s emulator-5554 shell bmgr run```
Outputs LogCat:
```02-21 09:52:09.409      880-891/system_process V/BackupManagerService? Scheduling immediate backup pass
02-21 09:52:09.409      880-895/system_process V/BackupManagerService? Running a backup pass
02-21 09:52:09.409      880-941/system_process V/BackupManagerService? clearing pending backups
02-21 09:52:09.409      880-941/system_process V/PerformBackupTask? Beginning backup of 8 targets
02-21 09:52:09.409      880-941/system_process I/PerformBackupTask? Initializing (wiping) backup state and transport storage
02-21 09:52:09.499      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on @pm@
02-21 09:52:09.519      880-941/system_process V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.531      880-941/system_process V/LocalTransport? performBackup() pkg=@pm@
02-21 09:52:09.549      880-941/system_process V/LocalTransport? Got change set key=com.android.sharedstoragebackup size=1208 key64=Y29tLmFuZHJvaWQuc2hhcmVkc3RvcmFnZWJhY2t1cA==
02-21 09:52:09.549      880-941/system_process V/LocalTransport? finishBackup()
02-21 09:52:09.549      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.android.calendar}
02-21 09:52:09.549    1172-1172/com.android.calendar V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c26cf0 com.android.calendar} backupAgent=com.android.calendar.CalendarBackupAgent mode=0}
02-21 09:52:09.549    1172-1172/com.android.calendar V/ActivityThread? Initializing agent class com.android.calendar.CalendarBackupAgent
02-21 09:52:09.549      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on com.android.calendar
02-21 09:52:09.559    1172-1184/com.android.calendar V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.559    1172-1172/com.android.calendar V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c59158 com.android.calendar} backupAgent=com.android.calendar.CalendarBackupAgent mode=0}
02-21 09:52:09.559      880-941/system_process V/LocalTransport? performBackup() pkg=com.android.calendar
02-21 09:52:09.559      880-941/system_process V/LocalTransport? finishBackup()
02-21 09:52:09.559      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.android.browser}
02-21 09:52:09.578      880-941/system_process I/ActivityManager? Start proc com.android.browser for backup com.android.browser/.BrowserBackupAgent: pid=1580 uid=10016 gids={3003, 1015}
02-21 09:52:09.779    1580-1580/com.android.browser V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c15630 com.android.browser} backupAgent=com.android.browser.BrowserBackupAgent mode=0}
02-21 09:52:09.789    1580-1580/com.android.browser V/ActivityThread? Initializing agent class com.android.browser.BrowserBackupAgent
02-21 09:52:09.789      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on com.android.browser
02-21 09:52:09.789    1580-1591/com.android.browser V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.789      880-941/system_process I/PerformBackupTask? no backup data written; not calling transport
02-21 09:52:09.789      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=android}
02-21 09:52:09.789      880-895/system_process V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c71b58 android} backupAgent=com.android.server.SystemBackupAgent mode=0}
02-21 09:52:09.789      880-895/system_process V/ActivityThread? Initializing agent class com.android.server.SystemBackupAgent
02-21 09:52:09.789      880-895/system_process D/BackupManagerService? agentConnected pkg=android agent=android.app.backup.BackupAgent$BackupServiceBinder@b3f6c620
02-21 09:52:09.789      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on android
02-21 09:52:09.789      880-941/system_process V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.799      880-895/system_process V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c71b58 android} backupAgent=com.android.server.SystemBackupAgent mode=0}
02-21 09:52:09.799      880-941/system_process V/LocalTransport? performBackup() pkg=android
02-21 09:52:09.799      880-941/system_process V/LocalTransport? finishBackup()
02-21 09:52:09.799      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.android.providers.userdictionary}
02-21 09:52:09.799    1065-1065/android.process.acore V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c43fb0 com.android.providers.userdictionary} backupAgent=com.android.providers.userdictionary.DictionaryBackupAgent mode=0}
02-21 09:52:09.799    1065-1065/android.process.acore V/ActivityThread? Initializing agent class com.android.providers.userdictionary.DictionaryBackupAgent
02-21 09:52:09.799      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on com.android.providers.userdictionary
02-21 09:52:09.799    1065-1092/android.process.acore V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.799      880-941/system_process I/PerformBackupTask? no backup data written; not calling transport
02-21 09:52:09.808    1065-1065/android.process.acore V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c90c18 com.android.providers.userdictionary} backupAgent=com.android.providers.userdictionary.DictionaryBackupAgent mode=0}
02-21 09:52:09.808      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=br.com.arndroid.etdiet}
02-21 09:52:09.808    1505-1505/br.com.arndroid.etdiet V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3d8e990 br.com.arndroid.etdiet} backupAgent=br.com.arndroid.etdiet.backup.android.AndroidBackupAgentHelper mode=0}
02-21 09:52:09.808    1505-1505/br.com.arndroid.etdiet V/ActivityThread? Initializing agent class br.com.arndroid.etdiet.backup.android.AndroidBackupAgentHelper
02-21 09:52:09.808      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on br.com.arndroid.etdiet
02-21 09:52:09.819    1580-1580/com.android.browser V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c5bd50 com.android.browser} backupAgent=com.android.browser.BrowserBackupAgent mode=0}
02-21 09:52:09.829    1505-1516/br.com.arndroid.etdiet V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.829    1505-1516/br.com.arndroid.etdiet D/BackupHelperDispatcher? handling new helper 'PREFERENCES_BACKUP'
02-21 09:52:09.829    1505-1505/br.com.arndroid.etdiet V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3d37578 br.com.arndroid.etdiet} backupAgent=br.com.arndroid.etdiet.backup.android.AndroidBackupAgentHelper mode=0}
02-21 09:52:09.829      880-941/system_process V/LocalTransport? performBackup() pkg=br.com.arndroid.etdiet
02-21 09:52:09.829      880-941/system_process V/LocalTransport? Got change set key=PREFERENCES_BACKUP:etd_preferences size=285 key64=UFJFRkVSRU5DRVNfQkFDS1VQOmV0ZF9wcmVmZXJlbmNlcw==
02-21 09:52:09.829      880-941/system_process V/LocalTransport? finishBackup()
02-21 09:52:09.839      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.android.inputmethod.latin}
02-21 09:52:09.839    1003-1003/com.android.inputmethod.latin V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c9cab0 com.android.inputmethod.latin} backupAgent=com.android.inputmethod.latin.BackupAgent mode=0}
02-21 09:52:09.839    1003-1003/com.android.inputmethod.latin V/ActivityThread? Initializing agent class com.android.inputmethod.latin.BackupAgent
02-21 09:52:09.839      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on com.android.inputmethod.latin
02-21 09:52:09.839    1003-1557/com.android.inputmethod.latin V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.839    1003-1003/com.android.inputmethod.latin V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c9faf0 com.android.inputmethod.latin} backupAgent=com.android.inputmethod.latin.BackupAgent mode=0}
02-21 09:52:09.849      880-941/system_process I/PerformBackupTask? no backup data written; not calling transport
02-21 09:52:09.849      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.android.sharedstoragebackup}
02-21 09:52:09.859      880-941/system_process I/ActivityManager? Start proc com.android.sharedstoragebackup for backup com.android.sharedstoragebackup/.SharedStorageAgent: pid=1614 uid=10022 gids={1015, 1023}
02-21 09:52:09.879    1614-1614/com.android.sharedstoragebackup V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c141d0 com.android.sharedstoragebackup} backupAgent=com.android.sharedstoragebackup.SharedStorageAgent mode=0}
02-21 09:52:09.889    1614-1614/com.android.sharedstoragebackup V/ActivityThread? Initializing agent class com.android.sharedstoragebackup.SharedStorageAgent
02-21 09:52:09.889      880-941/system_process D/BackupManagerService? awaiting agent for ApplicationInfo{b3f88038 com.android.sharedstoragebackup}
02-21 09:52:09.889     880-1442/system_process D/BackupManagerService? agentConnected pkg=com.android.sharedstoragebackup agent=android.os.BinderProxy@b4578f58
02-21 09:52:09.889      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on com.android.sharedstoragebackup
02-21 09:52:09.889    1614-1625/com.android.sharedstoragebackup V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.889    1614-1614/com.android.sharedstoragebackup V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3c1cdf8 com.android.sharedstoragebackup} backupAgent=com.android.sharedstoragebackup.SharedStorageAgent mode=0}
02-21 09:52:09.899      880-941/system_process I/PerformBackupTask? no backup data written; not calling transport
02-21 09:52:09.899      880-941/system_process D/PerformBackupTask? starting agent for backup of BackupRequest{pkg=com.android.providers.settings}
02-21 09:52:09.899      880-895/system_process V/ActivityThread? handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3f812b8 com.android.providers.settings} backupAgent=com.android.providers.settings.SettingsBackupAgent mode=0}
02-21 09:52:09.899      880-895/system_process V/ActivityThread? Initializing agent class com.android.providers.settings.SettingsBackupAgent
02-21 09:52:09.899      880-895/system_process D/BackupManagerService? agentConnected pkg=com.android.providers.settings agent=android.app.backup.BackupAgent$BackupServiceBinder@b449fe28
02-21 09:52:09.899      880-941/system_process D/PerformBackupTask? processOneBackup doBackup() on com.android.providers.settings
02-21 09:52:09.899      880-941/system_process V/BackupServiceBinder? doBackup() invoked
02-21 09:52:09.899      880-941/system_process W/SettingsBackupAgent? Couldn't backup /data/misc/wifi/ipconfig.txt
02-21 09:52:09.899      880-895/system_process V/ActivityThread? handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{b3f812b8 com.android.providers.settings} backupAgent=com.android.providers.settings.SettingsBackupAgent mode=0}
02-21 09:52:09.910      880-941/system_process V/LocalTransport? performBackup() pkg=com.android.providers.settings
02-21 09:52:09.910      880-941/system_process V/LocalTransport? finishBackup()
02-21 09:52:09.910      880-941/system_process I/PerformBackupTask? Backup pass finished.```

After app uninstall and reinstall the shared preferences are restored to user edited values. :-)

**Comment by ARNdroid** [comment]
It seems to be a very unreliable Android feature.

Nevertheless, our implementation is correct. Go ahead and commit.
